// routes/seedRoutes.ts
import { Router, Request, Response } from 'express';
import { Destination } from '../models/Destination';

const router = Router();

router.get('/seed', async (_req: Request, res: Response) => {
  try {
    await Destination.deleteMany({});         // clear old data

  const created = await Destination.insertMany([
    // ANDHRA PRADESH
    {
      name: 'Andhra Pradesh, India',
      country: 'India',
      tagline: 'Coastline, temples and valleys',
      image: 'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
      description:
        'Andhra Pradesh offers a mix of beaches, hill stations and famous temples.',
      topAttractions: ['Visakhapatnam', 'Araku Valley', 'Tirupati'],
      themes: ['beach', 'spiritual', 'nature'],
      popularityScore: 82,
      visitCount: 640,
      latitude: 15.9129,
      longitude: 79.7400,
      hotels: [
        {
          name: 'Vizag Sea View Resort',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 3200,
          priceTo: 5200,
          currency: 'INR',
          address: 'RK Beach, Visakhapatnam',
          description: 'Beachfront stay with sea-facing rooms and rooftop dining.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Sea view', 'Breakfast included', 'Free Wi-Fi'],
          latitude: 17.7160,
          longitude: 83.3160,
        },
        {
          name: 'Araku Valley Hill Retreat',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2800,
          priceTo: 4300,
          currency: 'INR',
          address: 'Araku Valley, Andhra Pradesh',
          description: 'Quiet resort surrounded by coffee plantations and hills.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Mountain view', 'Bonfire', 'Restaurant'],
          latitude: 18.3270,
          longitude: 82.8790,
        },
        {
          name: 'Tirupati Temple View Hotel',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4100,
          currency: 'INR',
          address: 'Near Tirumala Road, Tirupati',
          description: 'Comfortable stay with easy access to the temple and city.',
          images: [
            'https://images.pexels.com/photos/271639/pexels-photo-271639.jpeg',
          ],
          amenities: ['Breakfast', 'Shuttle assistance', 'Free Wi-Fi'],
          latitude: 13.6288,
          longitude: 79.4192,
        },
        {
          name: 'Budget Inn Vizag Central',
          rating: 3.9,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1800,
          currency: 'INR',
          address: 'Daba Gardens, Visakhapatnam',
          description: 'Simple rooms in central Vizag, ideal for short city stays.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['24/7 reception', 'Wi-Fi'],
          latitude: 17.7200,
          longitude: 83.3000,
        },
        {
          name: 'Heritage Stay Tirupati',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2200,
          priceTo: 3600,
          currency: 'INR',
          address: 'Tirupati Town',
          description: 'Traditional style hotel with vegetarian restaurant.',
          images: [
            'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg',
          ],
          amenities: ['Pure veg restaurant', 'Room service'],
          latitude: 13.6300,
          longitude: 79.4200,
        },
      ],
    },

    // ARUNACHAL PRADESH
    {
      name: 'Arunachal Pradesh, India',
      country: 'India',
      tagline: 'Land of rising sun and monasteries',
      image: 'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
      description:
        'Arunachal Pradesh is known for its high mountains, monasteries and unique tribal culture.',
      topAttractions: ['Tawang', 'Ziro Valley', 'Itanagar'],
      themes: ['mountain', 'culture', 'nature'],
      popularityScore: 78,
      visitCount: 410,
      latitude: 28.2180,
      longitude: 94.7278,
      hotels: [
        {
          name: 'Tawang Monastery View Hotel',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 3000,
          priceTo: 4600,
          currency: 'INR',
          address: 'Near Tawang Monastery, Tawang',
          description: 'Cosy stay with views of the monastery and snow peaks.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Mountain view', 'Heater', 'Breakfast'],
          latitude: 27.5860,
          longitude: 91.8750,
        },
        {
          name: 'Ziro Valley Eco Cottages',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 2800,
          priceTo: 4300,
          currency: 'INR',
          address: 'Ziro, Arunachal Pradesh',
          description: 'Eco-friendly cottages with wooden interiors in green fields.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Local food', 'Bonfire', 'Guided walks'],
          latitude: 27.5945,
          longitude: 93.8285,
        },
        {
          name: 'Itanagar City Hotel',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2200,
          priceTo: 3400,
          currency: 'INR',
          address: 'Itanagar',
          description: 'City hotel with comfortable rooms and in-house dining.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Wi-Fi', 'Restaurant', 'Parking'],
          latitude: 27.0844,
          longitude: 93.6053,
        },
        {
          name: 'Budget Guest House Tawang',
          rating: 3.8,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Tawang Town',
          description: 'Warm homely guest house run by local family.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Home-cooked meals', 'Heater on request'],
          latitude: 27.5860,
          longitude: 91.8750,
        },
        {
          name: 'Ziro Backpackers Lodge',
          rating: 4.1,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1600,
          currency: 'INR',
          address: 'Near market, Ziro',
          description: 'Simple dorms and rooms popular with backpackers.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Dorm beds', 'Common area'],
          latitude: 27.5950,
          longitude: 93.8300,
        },
      ],
    },

    // ASSAM
    {
      name: 'Assam, India',
      country: 'India',
      tagline: 'Tea gardens and river islands',
      image: 'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
      description:
        'Assam is famous for tea gardens, wildlife sanctuaries and the mighty Brahmaputra.',
      topAttractions: ['Kaziranga National Park', 'Guwahati', 'Majuli'],
      themes: ['wildlife', 'nature', 'culture'],
      popularityScore: 80,
      visitCount: 590,
      latitude: 26.2006,
      longitude: 92.9376,
      hotels: [
        {
          name: 'Kaziranga Jungle Lodge',
          rating: 4.6,
          priceLevel: '$$',
          priceFrom: 3800,
          priceTo: 6200,
          currency: 'INR',
          address: 'Kaziranga National Park, Assam',
          description: 'Jungle lodge with safari booking and cottage-style rooms.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Safari desk', 'Restaurant', 'Bonfire'],
          latitude: 26.5775,
          longitude: 93.1711,
        },
        {
          name: 'Guwahati Riverside Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'Near Brahmaputra, Guwahati',
          description: 'Riverside hotel with city access and scenic views.',
          images: [
            'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
          ],
          amenities: ['River view', 'Breakfast', 'Parking'],
          latitude: 26.1800,
          longitude: 91.7400,
        },
        {
          name: 'Majuli Island Homestay',
          rating: 4.4,
          priceLevel: '$',
          priceFrom: 1100,
          priceTo: 2200,
          currency: 'INR',
          address: 'Majuli, Assam',
          description: 'Traditional bamboo houses offering a village stay experience.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Local food', 'Cultural programs'],
          latitude: 26.9567,
          longitude: 94.2037,
        },
        {
          name: 'Guwahati City Inn',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2000,
          priceTo: 3300,
          currency: 'INR',
          address: 'Paltan Bazar, Guwahati',
          description: 'Central hotel close to railway and main markets.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Wi-Fi', 'Restaurant'],
          latitude: 26.1770,
          longitude: 91.7440,
        },
        {
          name: 'Kaziranga Budget Camp',
          rating: 3.9,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Near Kaziranga Gate',
          description: 'Basic tents and rooms with easy park access.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Campfire', 'Safari help'],
          latitude: 26.5800,
          longitude: 93.1700,
        },
      ],
    },

    // BIHAR
    {
      name: 'Bihar, India',
      country: 'India',
      tagline: 'Ancient centers of learning and faith',
      image: 'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
      description: 'Bihar holds many important Buddhist and historical sites.',
      topAttractions: ['Bodh Gaya', 'Patna', 'Rajgir'],
      themes: ['spiritual', 'heritage', 'city'],
      popularityScore: 76,
      visitCount: 430,
      latitude: 25.0961,
      longitude: 85.3131,
      hotels: [
        {
          name: 'Bodh Gaya Temple Stay',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'Near Mahabodhi Temple, Bodh Gaya',
          description: 'Peaceful hotel with garden and walking distance to temple.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Vegetarian meals', 'Meditation hall'],
          latitude: 24.6961,
          longitude: 84.9914,
        },
        {
          name: 'Patna Riverfront Hotel',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2300,
          priceTo: 3800,
          currency: 'INR',
          address: 'Patna, Bihar',
          description: 'Modern hotel with easy access to museums and ghats.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Wi-Fi', 'Restaurant', 'Parking'],
          latitude: 25.5941,
          longitude: 85.1376,
        },
        {
          name: 'Rajgir Hills Resort',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2400,
          priceTo: 3600,
          currency: 'INR',
          address: 'Rajgir, Bihar',
          description:
            'Resort surrounded by hills, close to ropeway and hot springs.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Garden', 'Restaurant'],
          latitude: 25.0276,
          longitude: 85.4218,
        },
        {
          name: 'Budget Lodge Patna Junction',
          rating: 3.7,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1600,
          currency: 'INR',
          address: 'Near Patna Junction',
          description: 'Basic lodge ideal for overnight transit stays.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['24/7 front desk'],
          latitude: 25.6090,
          longitude: 85.1410,
        },
        {
          name: 'Bodh Gaya Guest House',
          rating: 4.0,
          priceLevel: '$',
          priceFrom: 1000,
          priceTo: 1800,
          currency: 'INR',
          address: 'Bodh Gaya Town',
          description: 'Simple rooms run by local family, close to cafes.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Home-cooked food', 'Wi-Fi'],
          latitude: 24.6965,
          longitude: 84.9870,
        },
      ],
    },

    // CHHATTISGARH
    {
      name: 'Chhattisgarh, India',
      country: 'India',
      tagline: 'Waterfalls, forests and tribal culture',
      image: 'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
      description:
        'Chhattisgarh is known for waterfalls, dense forests and ancient temples.',
      topAttractions: ['Chitrakote Falls', 'Jagdalpur', 'Barnawapara Wildlife Sanctuary'],
      themes: ['nature', 'wildlife', 'culture'],
      popularityScore: 74,
      visitCount: 360,
      latitude: 21.2787,
      longitude: 81.8661,
      hotels: [
        {
          name: 'Chitrakote Falls Resort',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 3900,
          currency: 'INR',
          address: 'Near Chitrakote Falls, Bastar',
          description: 'Resort with views of the famous waterfall and greenery.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Guided tours', 'Restaurant'],
          latitude: 18.9810,
          longitude: 81.6640,
        },
        {
          name: 'Jagdalpur City Hotel',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2000,
          priceTo: 3200,
          currency: 'INR',
          address: 'Jagdalpur, Chhattisgarh',
          description: 'Comfortable stay close to local markets and attractions.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Wi-Fi', 'Parking'],
          latitude: 19.0740,
          longitude: 82.0080,
        },
        {
          name: 'Barnawapara Jungle Camp',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2400,
          priceTo: 3600,
          currency: 'INR',
          address: 'Barnawapara Wildlife Sanctuary',
          description: 'Jungle camp with cottages and nature walks.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Safari desk', 'Bonfire'],
          latitude: 21.4870,
          longitude: 82.1160,
        },
        {
          name: 'Budget Lodge Raipur',
          rating: 3.7,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Raipur City',
          description: 'Budget-friendly lodge for quick city visits.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Wi-Fi', '24/7 front desk'],
          latitude: 21.2514,
          longitude: 81.6296,
        },
        {
          name: 'Heritage Stay Bastar',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2100,
          priceTo: 3300,
          currency: 'INR',
          address: 'Bastar Region',
          description: 'Traditional style stay highlighting local art and culture.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Cultural shows', 'Local cuisine'],
          latitude: 19.0740,
          longitude: 82.0080,
        },
      ],
    },

    // GOA
    {
      name: 'Goa, India',
      country: 'India',
      tagline: 'Beaches and sunsets',
      image: 'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
      description:
        'Goa is known for its beautiful beaches, nightlife and relaxed vibe.',
      topAttractions: ['Baga & Calangute', 'Panaji', 'Palolem'],
      themes: ['beach', 'party', 'relax'],
      popularityScore: 90,
      visitCount: 980,
      latitude: 15.2993,
      longitude: 74.1240,
      hotels: [
        {
          name: 'Sea Breeze Resort Baga',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 3500,
          priceTo: 5500,
          currency: 'INR',
          address: 'Baga Beach, North Goa',
          description: 'Beachside resort with pool and live music nights.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Pool', 'Breakfast', 'Beach access'],
          latitude: 15.5569,
          longitude: 73.7517,
        },
        {
          name: 'Calangute Beachfront Villas',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 4200,
          priceTo: 6500,
          currency: 'INR',
          address: 'Calangute, Goa',
          description: 'Private villas ideal for groups and families near the beach.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Kitchenette', 'Parking'],
          latitude: 15.5439,
          longitude: 73.7553,
        },
        {
          name: 'Goa Backpackers Hostel',
          rating: 4.1,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1600,
          currency: 'INR',
          address: 'Arpora, North Goa',
          description: 'Lively hostel with dorms, bar and common lounge.',
          images: [
            'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg',
          ],
          amenities: ['Dorm beds', 'Events & games'],
          latitude: 15.5750,
          longitude: 73.7640,
        },
        {
          name: 'Panaji City Hotel',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'Panaji, Goa',
          description:
            'City hotel with easy access to churches, market and riverfront.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Wi-Fi', 'Restaurant'],
          latitude: 15.4909,
          longitude: 73.8278,
        },
        {
          name: 'Palolem Beach Huts',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 2800,
          priceTo: 4300,
          currency: 'INR',
          address: 'Palolem, South Goa',
          description: 'Cute wooden huts right on the calm Palolem beach.',
          images: [
            'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
          ],
          amenities: ['Beach access', 'Restaurant'],
          latitude: 15.0099,
          longitude: 74.0230,
        },
        {
          name: 'Budget Inn Calangute',
          rating: 3.8,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Calangute Market Road',
          description:
            'Simple rooms for budget travellers close to shops and cafes.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Wi-Fi'],
          latitude: 15.5430,
          longitude: 73.7580,
        },
      ],
    },

    // GUJARAT
    {
      name: 'Gujarat, India',
      country: 'India',
      tagline: 'White desert, lions and heritage cities',
      image: 'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
      description:
        'Gujarat offers unique landscapes, temples and wildlife experiences.',
      topAttractions: ['Rann of Kutch', 'Gir National Park', 'Ahmedabad'],
      themes: ['desert', 'wildlife', 'heritage'],
      popularityScore: 84,
      visitCount: 650,
      latitude: 22.2587,
      longitude: 71.1924,
      hotels: [
        {
          name: 'White Rann Desert Camp',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 3800,
          priceTo: 6200,
          currency: 'INR',
          address: 'Dhordo, Kutch',
          description: 'Traditional tents with cultural evenings in the salt desert.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Cultural shows', 'Meals included'],
          latitude: 23.9966,
          longitude: 69.7313,
        },
        {
          name: 'Gir Jungle Resort',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 3600,
          priceTo: 5800,
          currency: 'INR',
          address: 'Sasan Gir, Gujarat',
          description: 'Resort with cottages and easy access to lion safaris.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Safari desk', 'Pool'],
          latitude: 21.1667,
          longitude: 70.8000,
        },
        {
          name: 'Ahmedabad Heritage Hotel',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'Old City, Ahmedabad',
          description: 'Haveli-style stay close to pols and heritage walk routes.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Wi-Fi', 'Breakfast'],
          latitude: 23.0225,
          longitude: 72.5714,
        },
        {
          name: 'Budget Stay Ahmedabad',
          rating: 3.8,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Navrangpura, Ahmedabad',
          description: 'Simple and clean city hotel with compact rooms.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Wi-Fi', 'Parking'],
          latitude: 23.0410,
          longitude: 72.5600,
        },
        {
          name: 'Bhuj City Inn',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2200,
          priceTo: 3600,
          currency: 'INR',
          address: 'Bhuj, Kutch',
          description:
            'Comfortable base for exploring Kutch region and handicraft villages.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Restaurant', 'Tour help'],
          latitude: 23.2419,
          longitude: 69.6660,
        },
      ],
    },

    // HARYANA
    {
      name: 'Haryana, India',
      country: 'India',
      tagline: 'Business hubs and historic fields',
      image: 'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
      description:
        'Haryana mixes modern business cities with important historic and pilgrimage spots.',
      topAttractions: ['Gurugram', 'Kurukshetra', 'Pinjore Gardens'],
      themes: ['city', 'heritage', 'family'],
      popularityScore: 75,
      visitCount: 420,
      latitude: 29.0588,
      longitude: 76.0856,
      hotels: [
        {
          name: 'Gurugram Business Hotel',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 3600,
          priceTo: 5800,
          currency: 'INR',
          address: 'Cyber City, Gurugram',
          description: 'Modern hotel close to offices and malls.',
          images: [
            'https://images.pexels.com/photos/37347/office-night-computer-innovation-37347.jpeg',
          ],
          amenities: ['Wi-Fi', 'Gym', 'Breakfast'],
          latitude: 28.4946,
          longitude: 77.0888,
        },
        {
          name: 'Kurukshetra Pilgrim Stay',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2200,
          priceTo: 3400,
          currency: 'INR',
          address: 'Kurukshetra, Haryana',
          description: 'Hotel near holy sites and lakes of Kurukshetra.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Vegetarian meals', 'Parking'],
          latitude: 29.9695,
          longitude: 76.8783,
        },
        {
          name: 'Pinjore Garden Resort',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 3800,
          currency: 'INR',
          address: 'Near Pinjore Gardens',
          description: 'Green resort ideal for families and weekend trips.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Garden', 'Play area'],
          latitude: 30.7976,
          longitude: 76.9103,
        },
        {
          name: 'Budget Inn Gurugram',
          rating: 3.8,
          priceLevel: '$',
          priceFrom: 1000,
          priceTo: 1900,
          currency: 'INR',
          address: 'Sikanderpur, Gurugram',
          description: 'Budget hotel close to metro and offices.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Wi-Fi'],
          latitude: 28.4815,
          longitude: 77.0910,
        },
        {
          name: 'Manesar Highway Motel',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2000,
          priceTo: 3200,
          currency: 'INR',
          address: 'NH8, Manesar',
          description: 'Highway hotel popular with road trip travellers.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Parking', 'Restaurant'],
          latitude: 28.3570,
          longitude: 76.9380,
        },
      ],
    },

    // HIMACHAL PRADESH
    {
      name: 'Himachal Pradesh, India',
      country: 'India',
      tagline: 'Hill stations and snow peaks',
      image: 'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
      description:
        'Himachal Pradesh is a favourite for hill stations, trekking and snow.',
      topAttractions: ['Manali', 'Shimla', 'Dharamshala'],
      themes: ['mountain', 'adventure', 'nature'],
      popularityScore: 88,
      visitCount: 920,
      latitude: 31.1048,
      longitude: 77.1734,
      hotels: [
        {
          name: 'Manali Valley Resort',
          rating: 4.6,
          priceLevel: '$$',
          priceFrom: 3200,
          priceTo: 5400,
          currency: 'INR',
          address: 'Old Manali, Himachal Pradesh',
          description: 'Resort with beautiful valley views and cosy rooms.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Mountain view', 'Bonfire'],
          latitude: 32.2432,
          longitude: 77.1892,
        },
        {
          name: 'Shimla Mall Road Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 3000,
          priceTo: 4800,
          currency: 'INR',
          address: 'Near Mall Road, Shimla',
          description: 'Central hotel just a short walk from the Ridge and Mall.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Heater', 'Restaurant'],
          latitude: 31.1048,
          longitude: 77.1734,
        },
        {
          name: 'Dharamshala Mountain Lodge',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 2800,
          priceTo: 4300,
          currency: 'INR',
          address: 'McLeod Ganj, Dharamshala',
          description:
            'Stay with views of Dhauladhar range and monastery access.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Balcony', 'Cafe'],
          latitude: 32.2426,
          longitude: 76.3210,
        },
        {
          name: 'Backpackers Hub Manali',
          rating: 4.2,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Old Manali',
          description: 'Popular hostel with cafe, music nights and common space.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Dorm beds', 'Wi-Fi'],
          latitude: 32.2440,
          longitude: 77.1890,
        },
        {
          name: 'Shimla Budget Stay',
          rating: 3.9,
          priceLevel: '$',
          priceFrom: 1000,
          priceTo: 1900,
          currency: 'INR',
          address: 'Shimla Town',
          description: 'Simple heated rooms for budget travellers.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Heater', 'Room service'],
          latitude: 31.1048,
          longitude: 77.1734,
        },
      ],
    },

    // TAMIL NADU
    {
      name: 'Tamil Nadu, India',
      country: 'India',
      tagline: 'Temples, beaches and hill stations',
      image: 'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
      description:
        'Tamil Nadu is rich in temples, heritage cities and cool hill towns.',
      topAttractions: ['Chennai', 'Ooty', 'Kodaikanal'],
      themes: ['spiritual', 'city', 'hill-station'],
      popularityScore: 87,
      visitCount: 880,
      latitude: 11.1271,
      longitude: 78.6569,
      hotels: [
        {
          name: 'Chennai Marina Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2800,
          priceTo: 4400,
          currency: 'INR',
          address: 'Near Marina Beach, Chennai',
          description: 'Modern hotel close to the beach and city center.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Wi-Fi', 'Restaurant'],
          latitude: 13.0500,
          longitude: 80.2824,
        },
        {
          name: 'Ooty Lakeview Resort',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 3200,
          priceTo: 5200,
          currency: 'INR',
          address: 'Near Ooty Lake, Ooty',
          description: 'Resort with garden and great views of the hills.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Bonfire', 'Breakfast'],
          latitude: 11.4064,
          longitude: 76.6932,
        },
        {
          name: 'Kodaikanal Cliff Hotel',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 3000,
          priceTo: 4800,
          currency: 'INR',
          address: 'Coakers Walk, Kodaikanal',
          description: 'Stay on the cliffs with valley views and cosy rooms.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Mountain view', 'Restaurant'],
          latitude: 10.2381,
          longitude: 77.4892,
        },
        {
          name: 'Budget Inn T Nagar',
          rating: 3.9,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'T Nagar, Chennai',
          description: 'Budget hotel near main shopping streets.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Wi-Fi'],
          latitude: 13.0418,
          longitude: 80.2345,
        },
        {
          name: 'Ooty Backpackers Hostel',
          rating: 4.1,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1600,
          currency: 'INR',
          address: 'Near Charring Cross, Ooty',
          description: 'Hostel with dorms, games and a cafe.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Dorm beds', 'Common lounge'],
          latitude: 11.4110,
          longitude: 76.6950,
        },
      ],
    },

    // ------------------------
    // REMAINING INDIAN STATES
    // ------------------------

    // JHARKHAND
    {
      name: 'Jharkhand, India',
      country: 'India',
      tagline: 'Waterfalls, forests and steel cities',
      image: 'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
      description:
        'Jharkhand offers scenic waterfalls, forests and important industrial towns.',
      topAttractions: ['Ranchi', 'Jamshedpur', 'Deoghar'],
      themes: ['nature', 'city', 'spiritual'],
      popularityScore: 77,
      visitCount: 380,
      latitude: 23.6102,
      longitude: 85.2799,
      hotels: [
        {
          name: 'Ranchi Lakeview Hotel',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2300,
          priceTo: 3600,
          currency: 'INR',
          address: 'Near Ranchi Lake, Ranchi',
          description: 'City hotel with easy access to parks and markets.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Wi-Fi', 'Breakfast'],
          latitude: 23.3685,
          longitude: 85.3320,
        },
        {
          name: 'Falls View Resort Ranchi',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 3900,
          currency: 'INR',
          address: 'Near Hundru Falls, Ranchi',
          description: 'Resort near waterfalls with greenery all around.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Garden', 'Restaurant'],
          latitude: 23.4560,
          longitude: 85.4400,
        },
        {
          name: 'Jamshedpur Steel City Inn',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2200,
          priceTo: 3400,
          currency: 'INR',
          address: 'Bistupur, Jamshedpur',
          description: 'Comfortable business hotel in the heart of the city.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Wi-Fi', 'Parking'],
          latitude: 22.7930,
          longitude: 86.1840,
        },
        {
          name: 'Deoghar Temple View Lodge',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2000,
          priceTo: 3200,
          currency: 'INR',
          address: 'Near Baidyanath Temple, Deoghar',
          description: 'Pilgrim-friendly hotel at walking distance from the temple.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Vegetarian meals', 'Hot water'],
          latitude: 24.4932,
          longitude: 86.6940,
        },
        {
          name: 'Budget Stay Ranchi Station',
          rating: 3.7,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1500,
          currency: 'INR',
          address: 'Near Railway Station, Ranchi',
          description: 'Simple lodge ideal for overnight stays.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['24/7 front desk'],
          latitude: 23.3623,
          longitude: 85.3250,
        },
      ],
    },

    // KARNATAKA
    {
      name: 'Karnataka, India',
      country: 'India',
      tagline: 'IT hubs, palaces and coffee hills',
      image: 'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
      description:
        'Karnataka has modern cities, royal heritage and lush hill stations.',
      topAttractions: ['Bengaluru', 'Mysuru', 'Coorg'],
      themes: ['city', 'heritage', 'nature'],
      popularityScore: 89,
      visitCount: 940,
      latitude: 15.3173,
      longitude: 75.7139,
      hotels: [
        {
          name: 'Bengaluru Tech Park Hotel',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 3200,
          priceTo: 5200,
          currency: 'INR',
          address: 'Outer Ring Road, Bengaluru',
          description: 'Business-friendly hotel near major IT parks.',
          images: [
            'https://images.pexels.com/photos/37347/office-night-computer-innovation-37347.jpeg',
          ],
          amenities: ['Wi-Fi', 'Gym', 'Breakfast'],
          latitude: 12.9352,
          longitude: 77.6245,
        },
        {
          name: 'MG Road City Inn',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 3900,
          currency: 'INR',
          address: 'MG Road, Bengaluru',
          description: 'Central hotel close to pubs, malls and metro.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Parking', 'Restaurant'],
          latitude: 12.9738,
          longitude: 77.6123,
        },
        {
          name: 'Mysuru Palace View Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2800,
          priceTo: 4300,
          currency: 'INR',
          address: 'Near Mysore Palace, Mysuru',
          description: 'Stay close to the palace and main markets.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Breakfast', 'Wi-Fi'],
          latitude: 12.3052,
          longitude: 76.6552,
        },
        {
          name: 'Coorg Coffee Estate Resort',
          rating: 4.6,
          priceLevel: '$$',
          priceFrom: 3400,
          priceTo: 5600,
          currency: 'INR',
          address: 'Madikeri, Coorg',
          description: 'Resort inside coffee plantations with nature trails.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Bonfire', 'Guided walks'],
          latitude: 12.4244,
          longitude: 75.7382,
        },
        {
          name: 'Backpackers Hostel Bengaluru',
          rating: 4.2,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Koramangala, Bengaluru',
          description: 'Youth hostel with shared dorms and common lounge.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Dorm beds', 'Common kitchen'],
          latitude: 12.9355,
          longitude: 77.6240,
        },
      ],
    },

    // KERALA
    {
      name: 'Kerala, India',
      country: 'India',
      tagline: 'Backwaters, beaches and greenery',
      image: 'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
      description:
        'Kerala is known as God’s Own Country with backwaters, hills and beaches.',
      topAttractions: ['Munnar', 'Alleppey', 'Kochi'],
      themes: ['nature', 'backwaters', 'beach'],
      popularityScore: 91,
      visitCount: 960,
      latitude: 10.8505,
      longitude: 76.2711,
      hotels: [
        {
          name: 'Munnar Tea Hills Resort',
          rating: 4.6,
          priceLevel: '$$',
          priceFrom: 3200,
          priceTo: 5200,
          currency: 'INR',
          address: 'Munnar, Kerala',
          description: 'Hill resort surrounded by tea gardens and misty views.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Bonfire', 'Guided walks'],
          latitude: 10.0892,
          longitude: 77.0597,
        },
        {
          name: 'Alleppey Backwater Houseboat Stay',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 3800,
          priceTo: 6200,
          currency: 'INR',
          address: 'Punnamada, Alleppey',
          description: 'Traditional houseboat stay cruising the backwaters.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['All meals', 'Sunset cruise'],
          latitude: 9.4981,
          longitude: 76.3388,
        },
        {
          name: 'Fort Kochi Heritage Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2800,
          priceTo: 4300,
          currency: 'INR',
          address: 'Fort Kochi, Kochi',
          description: 'Colonial style hotel near Chinese fishing nets.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Breakfast', 'Wi-Fi'],
          latitude: 9.9666,
          longitude: 76.2425,
        },
        {
          name: 'Kochi City Budget Inn',
          rating: 3.9,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Ernakulam, Kochi',
          description: 'Simple and clean rooms near shopping areas.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Wi-Fi'],
          latitude: 9.9816,
          longitude: 76.2999,
        },
        {
          name: 'Alleppey Beachfront Cottages',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4100,
          currency: 'INR',
          address: 'Alleppey Beach, Kerala',
          description: 'Cottages just a short walk from the beach.',
          images: [
            'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
          ],
          amenities: ['Beach access', 'Restaurant'],
          latitude: 9.4980,
          longitude: 76.3380,
        },
      ],
    },

    // MADHYA PRADESH
    {
      name: 'Madhya Pradesh, India',
      country: 'India',
      tagline: 'Heart of India with forests and temples',
      image: 'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
      description:
        'Madhya Pradesh is known for wildlife parks, ancient temples and forts.',
      topAttractions: ['Khajuraho', 'Bhopal', 'Bandhavgarh'],
      themes: ['heritage', 'wildlife', 'city'],
      popularityScore: 83,
      visitCount: 620,
      latitude: 22.9734,
      longitude: 78.6569,
      hotels: [
        {
          name: 'Khajuraho Temple View Resort',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'Near Western Group of Temples, Khajuraho',
          description: 'Resort with garden and easy access to temples.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Wi-Fi', 'Restaurant'],
          latitude: 24.8318,
          longitude: 79.9199,
        },
        {
          name: 'Bhopal Lakeside Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2500,
          priceTo: 3900,
          currency: 'INR',
          address: 'Upper Lake, Bhopal',
          description: 'Hotel overlooking the lake, close to city attractions.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Breakfast', 'Parking'],
          latitude: 23.2599,
          longitude: 77.4126,
        },
        {
          name: 'Bandhavgarh Jungle Lodge',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 3200,
          priceTo: 5400,
          currency: 'INR',
          address: 'Near Tala Gate, Bandhavgarh',
          description: 'Stay close to the forest with safari support.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Safari desk', 'Bonfire'],
          latitude: 23.6920,
          longitude: 81.0250,
        },
        {
          name: 'Bhopal Budget Inn',
          rating: 3.8,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'MP Nagar, Bhopal',
          description: 'Budget lodge well connected to bus and rail.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Wi-Fi'],
          latitude: 23.2335,
          longitude: 77.4340,
        },
        {
          name: 'Khajuraho Backpackers Hostel',
          rating: 4.0,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1500,
          currency: 'INR',
          address: 'Khajuraho Town',
          description: 'Hostel with dorms, cafe and bike rentals.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Dorm beds', 'Common lounge'],
          latitude: 24.8318,
          longitude: 79.9199,
        },
      ],
    },

    // MAHARASHTRA
    {
      name: 'Maharashtra, India',
      country: 'India',
      tagline: 'Metros, forts and coastal drives',
      image: 'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
      description:
        'Maharashtra covers mega cities, hill stations and beautiful coastline.',
      topAttractions: ['Mumbai', 'Pune', 'Mahabaleshwar'],
      themes: ['city', 'hill-station', 'coast'],
      popularityScore: 90,
      visitCount: 1100,
      latitude: 19.7515,
      longitude: 75.7139,
      hotels: [
        {
          name: 'Mumbai Marine Drive Hotel',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 3800,
          priceTo: 6200,
          currency: 'INR',
          address: 'Marine Drive, Mumbai',
          description: 'Seafront hotel on the famous Queen’s Necklace.',
          images: [
            'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
          ],
          amenities: ['Sea view', 'Restaurant'],
          latitude: 18.9430,
          longitude: 72.8238,
        },
        {
          name: 'Bandra City Inn',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'Bandra West, Mumbai',
          description: 'Trendy hotel close to cafes and nightlife.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Wi-Fi', 'Breakfast'],
          latitude: 19.0544,
          longitude: 72.8402,
        },
        {
          name: 'Pune Koregaon Park Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4100,
          currency: 'INR',
          address: 'Koregaon Park, Pune',
          description: 'City hotel surrounded by greenery and eateries.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Parking', 'Restaurant'],
          latitude: 18.5362,
          longitude: 73.8938,
        },
        {
          name: 'Mahabaleshwar Valley Resort',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 3000,
          priceTo: 4800,
          currency: 'INR',
          address: 'Panchgani Road, Mahabaleshwar',
          description: 'Hill resort with valley views and strawberry farms nearby.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Bonfire', 'Kids play area'],
          latitude: 17.9307,
          longitude: 73.6477,
        },
        {
          name: 'Mumbai Budget Lodge Dadar',
          rating: 3.8,
          priceLevel: '$',
          priceFrom: 1000,
          priceTo: 1900,
          currency: 'INR',
          address: 'Dadar, Mumbai',
          description: 'Central budget hotel great for transit stays.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Wi-Fi'],
          latitude: 19.0144,
          longitude: 72.8420,
        },
      ],
    },

    // MANIPUR
    {
      name: 'Manipur, India',
      country: 'India',
      tagline: 'Floating lake islands and culture',
      image: 'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
      description:
        'Manipur is known for Loktak Lake, rolling hills and rich culture.',
      topAttractions: ['Imphal', 'Loktak Lake', 'Kangla Fort'],
      themes: ['nature', 'culture', 'city'],
      popularityScore: 72,
      visitCount: 300,
      latitude: 24.6637,
      longitude: 93.9063,
      hotels: [
        {
          name: 'Imphal City Hotel',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2200,
          priceTo: 3400,
          currency: 'INR',
          address: 'Thangal Bazar, Imphal',
          description: 'Comfortable city hotel near main market.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Wi-Fi', 'Parking'],
          latitude: 24.8103,
          longitude: 93.9402,
        },
        {
          name: 'Loktak Lake Eco Resort',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4000,
          currency: 'INR',
          address: 'Moirang, near Loktak Lake',
          description: 'Eco stay with views of floating islands.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Boating help', 'Local food'],
          latitude: 24.4975,
          longitude: 93.7836,
        },
        {
          name: 'Kangla Heritage Stay',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2300,
          priceTo: 3600,
          currency: 'INR',
          address: 'Near Kangla Fort, Imphal',
          description: 'Small hotel highlighting local art and culture.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Breakfast', 'Wi-Fi'],
          latitude: 24.8074,
          longitude: 93.9420,
        },
        {
          name: 'Imphal Budget Guest House',
          rating: 3.7,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1500,
          currency: 'INR',
          address: 'Imphal Town',
          description: 'Simple guest house run by a local family.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Home-cooked meals'],
          latitude: 24.8170,
          longitude: 93.9500,
        },
        {
          name: 'Loktak Backpackers Camp',
          rating: 4.0,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Near Loktak Lake shore',
          description: 'Tents and basic rooms for nature lovers.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Bonfire', 'Shared kitchen'],
          latitude: 24.5000,
          longitude: 93.7800,
        },
      ],
    },

    // MEGHALAYA
    {
      name: 'Meghalaya, India',
      country: 'India',
      tagline: 'Living root bridges and misty hills',
      image: 'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
      description:
        'Meghalaya is famous for waterfalls, caves and living root bridges.',
      topAttractions: ['Shillong', 'Cherrapunji', 'Dawki'],
      themes: ['nature', 'mountain', 'adventure'],
      popularityScore: 85,
      visitCount: 620,
      latitude: 25.4670,
      longitude: 91.3662,
      hotels: [
        {
          name: 'Shillong Hilltop Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4100,
          currency: 'INR',
          address: 'Laitumkhrah, Shillong',
          description: 'Hill city hotel with views and cosy rooms.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Wi-Fi', 'Breakfast'],
          latitude: 25.5788,
          longitude: 91.8933,
        },
        {
          name: 'Cherrapunji Misty Valley Resort',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 3200,
          priceTo: 5200,
          currency: 'INR',
          address: 'Sohra, Cherrapunji',
          description: 'Resort overlooking valleys and waterfalls.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Guided treks', 'Restaurant'],
          latitude: 25.2841,
          longitude: 91.7300,
        },
        {
          name: 'Dawki Riverside Camp',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2400,
          priceTo: 3800,
          currency: 'INR',
          address: 'Umngot River, Dawki',
          description: 'Tented camp beside crystal clear river.',
          images: [
            'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
          ],
          amenities: ['Boating help', 'Bonfire'],
          latitude: 25.1846,
          longitude: 92.0103,
        },
        {
          name: 'Shillong Backpackers Hostel',
          rating: 4.1,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1500,
          currency: 'INR',
          address: 'Police Bazaar, Shillong',
          description: 'Backpacker friendly hostel in central location.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Dorm beds', 'Common lounge'],
          latitude: 25.5735,
          longitude: 91.8820,
        },
        {
          name: 'Cherrapunji Budget Homestay',
          rating: 3.9,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Sohra village, Cherrapunji',
          description: 'Homestay with simple rooms and local food.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Home-cooked meals'],
          latitude: 25.2841,
          longitude: 91.7305,
        },
      ],
    },

    // MIZORAM
    {
      name: 'Mizoram, India',
      country: 'India',
      tagline: 'Green hills and quiet towns',
      image: 'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
      description:
        'Mizoram offers peaceful hill towns, viewpoints and unique culture.',
      topAttractions: ['Aizawl', 'Lunglei', 'Champhai'],
      themes: ['mountain', 'culture', 'nature'],
      popularityScore: 70,
      visitCount: 260,
      latitude: 23.1645,
      longitude: 92.9376,
      hotels: [
        {
          name: 'Aizawl City Hotel',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2200,
          priceTo: 3400,
          currency: 'INR',
          address: 'Central Aizawl',
          description: 'City stay with easy access to markets and viewpoints.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Wi-Fi', 'Breakfast'],
          latitude: 23.7271,
          longitude: 92.7176,
        },
        {
          name: 'Aizawl Viewpoint Lodge',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2300,
          priceTo: 3600,
          currency: 'INR',
          address: 'Hilltop area, Aizawl',
          description: 'Rooms with panoramic views of the hills.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Balcony', 'Room service'],
          latitude: 23.7300,
          longitude: 92.7200,
        },
        {
          name: 'Lunglei Hillside Resort',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2400,
          priceTo: 3800,
          currency: 'INR',
          address: 'Lunglei, Mizoram',
          description: 'Resort located on a hill with nature all around.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Garden', 'Restaurant'],
          latitude: 22.8800,
          longitude: 92.7300,
        },
        {
          name: 'Champhai Valley Homestay',
          rating: 4.0,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1600,
          currency: 'INR',
          address: 'Champhai town',
          description: 'Homestay with local hosts and simple rooms.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Home-cooked food'],
          latitude: 23.4562,
          longitude: 93.3284,
        },
        {
          name: 'Budget Guest House Aizawl',
          rating: 3.7,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1500,
          currency: 'INR',
          address: 'Aizawl market area',
          description: 'Budget guest house ideal for short stays.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Wi-Fi'],
          latitude: 23.7270,
          longitude: 92.7180,
        },
      ],
    },

    // NAGALAND
    {
      name: 'Nagaland, India',
      country: 'India',
      tagline: 'Hills, tribes and festivals',
      image: 'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
      description:
        'Nagaland is known for Hornbill festival, hill views and tribal culture.',
      topAttractions: ['Kohima', 'Dimapur', 'Dzükou Valley'],
      themes: ['culture', 'mountain', 'nature'],
      popularityScore: 73,
      visitCount: 290,
      latitude: 26.1584,
      longitude: 94.5624,
      hotels: [
        {
          name: 'Kohima City Hotel',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2200,
          priceTo: 3400,
          currency: 'INR',
          address: 'Near War Cemetery, Kohima',
          description: 'City hotel close to main sights in Kohima.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Wi-Fi', 'Breakfast'],
          latitude: 25.6747,
          longitude: 94.1095,
        },
        {
          name: 'Kisama Festival Lodge',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 3900,
          currency: 'INR',
          address: 'Near Hornbill Festival grounds, Kohima',
          description: 'Stay used by visitors during the Hornbill festival.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Parking', 'Restaurant'],
          latitude: 25.6000,
          longitude: 94.1300,
        },
        {
          name: 'Dimapur Business Inn',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2200,
          priceTo: 3500,
          currency: 'INR',
          address: 'Dimapur Town',
          description: 'Hotel convenient for business and transit stays.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Wi-Fi', 'Airport pickup (paid)'],
          latitude: 25.9063,
          longitude: 93.7276,
        },
        {
          name: 'Dzükou Valley Trekker Camp',
          rating: 4.3,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Dzükou trail base, Nagaland',
          description: 'Basic camp for trekkers heading to the valley.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Shared kitchen', 'Bonfire'],
          latitude: 25.6260,
          longitude: 94.1410,
        },
        {
          name: 'Budget Guest House Kohima',
          rating: 3.7,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1500,
          currency: 'INR',
          address: 'Kohima Town',
          description: 'Small guest house with homely feel.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Home-cooked meals'],
          latitude: 25.6747,
          longitude: 94.1095,
        },
      ],
    },

    // ODISHA
    {
      name: 'Odisha, India',
      country: 'India',
      tagline: 'Temples, beaches and lakes',
      image: 'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
      description:
        'Odisha is famous for Jagannath Temple, Konark and Chilika Lake.',
      topAttractions: ['Puri', 'Bhubaneswar', 'Chilika Lake'],
      themes: ['spiritual', 'beach', 'nature'],
      popularityScore: 82,
      visitCount: 580,
      latitude: 20.9517,
      longitude: 85.0985,
      hotels: [
        {
          name: 'Puri Sea View Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'Marine Drive Road, Puri',
          description: 'Beachfront hotel close to temple and sea.',
          images: [
            'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
          ],
          amenities: ['Sea view', 'Restaurant'],
          latitude: 19.8135,
          longitude: 85.8312,
        },
        {
          name: 'Jagannath Temple Lodge',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2300,
          priceTo: 3600,
          currency: 'INR',
          address: 'Grand Road, Puri',
          description: 'Pilgrim stay a short walk from the temple.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Vegetarian meals'],
          latitude: 19.8047,
          longitude: 85.8249,
        },
        {
          name: 'Bhubaneswar City Hotel',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2400,
          priceTo: 3800,
          currency: 'INR',
          address: 'Janpath, Bhubaneswar',
          description: 'Modern hotel close to temples and IT offices.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Wi-Fi', 'Parking'],
          latitude: 20.2961,
          longitude: 85.8245,
        },
        {
          name: 'Chilika Lakefront Resort',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4000,
          currency: 'INR',
          address: 'Satapada, Chilika',
          description: 'Resort offering boat rides and birdwatching.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Boating help', 'Restaurant'],
          latitude: 19.7450,
          longitude: 85.6400,
        },
        {
          name: 'Puri Budget Guest House',
          rating: 3.8,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1600,
          currency: 'INR',
          address: 'Puri Town',
          description: 'Simple rooms for budget pilgrims and families.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['24/7 front desk'],
          latitude: 19.8130,
          longitude: 85.8300,
        },
      ],
    },

    // PUNJAB
    {
      name: 'Punjab, India',
      country: 'India',
      tagline: 'Golden Temple and vibrant fields',
      image: 'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
      description:
        'Punjab offers important religious sites, food and rich culture.',
      topAttractions: ['Amritsar', 'Chandigarh', 'Ludhiana'],
      themes: ['spiritual', 'city', 'family'],
      popularityScore: 84,
      visitCount: 640,
      latitude: 31.1471,
      longitude: 75.3412,
      hotels: [
        {
          name: 'Golden Temple View Hotel',
          rating: 4.6,
          priceLevel: '$$',
          priceFrom: 2800,
          priceTo: 4400,
          currency: 'INR',
          address: 'Near Golden Temple, Amritsar',
          description:
            'Comfortable hotel within walking distance of Harmandir Sahib.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Breakfast', 'Wi-Fi'],
          latitude: 31.6200,
          longitude: 74.8765,
        },
        {
          name: 'Amritsar Wagah Border Inn',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2300,
          priceTo: 3600,
          currency: 'INR',
          address: 'On GT Road, Amritsar',
          description: 'Good option for visitors to Wagah ceremony.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Parking', 'Restaurant'],
          latitude: 31.6330,
          longitude: 74.8710,
        },
        {
          name: 'Chandigarh Sector 17 Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'Sector 17, Chandigarh',
          description: 'City hotel in the main shopping and business area.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Wi-Fi', 'Gym'],
          latitude: 30.7414,
          longitude: 76.7683,
        },
        {
          name: 'Ludhiana City Inn',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2200,
          priceTo: 3400,
          currency: 'INR',
          address: 'Ferozepur Road, Ludhiana',
          description: 'Business style hotel with banquet halls.',
          images: [
            'https://images.pexels.com/photos/37347/office-night-computer-innovation-37347.jpeg',
          ],
          amenities: ['Parking', 'Restaurant'],
          latitude: 30.9009,
          longitude: 75.8573,
        },
        {
          name: 'Amritsar Budget Guest House',
          rating: 3.8,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1600,
          currency: 'INR',
          address: 'Old City, Amritsar',
          description: 'Homely budget stay in narrow lanes of the city.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Home-cooked meals'],
          latitude: 31.6205,
          longitude: 74.8750,
        },
      ],
    },

    // RAJASTHAN
    {
      name: 'Rajasthan, India',
      country: 'India',
      tagline: 'Palaces, deserts and forts',
      image: 'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
      description:
        'Rajasthan is known for its royal palaces, desert safaris and colourful cities.',
      topAttractions: ['Jaipur', 'Udaipur', 'Jaisalmer'],
      themes: ['heritage', 'desert', 'romantic'],
      popularityScore: 92,
      visitCount: 1200,
      latitude: 27.0238,
      longitude: 74.2179,
      hotels: [
        {
          name: 'Jaipur City Palace Haveli',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 3200,
          priceTo: 5400,
          currency: 'INR',
          address: 'Old City, Jaipur',
          description: 'Heritage haveli stay with Rajasthani decor.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Breakfast', 'Cultural shows'],
          latitude: 26.9239,
          longitude: 75.8267,
        },
        {
          name: 'Udaipur Lake Pichola Hotel',
          rating: 4.6,
          priceLevel: '$$',
          priceFrom: 3400,
          priceTo: 5600,
          currency: 'INR',
          address: 'Lake Pichola, Udaipur',
          description: 'Lakeside hotel with rooftop views and boat access.',
          images: [
            'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
          ],
          amenities: ['Rooftop restaurant', 'Wi-Fi'],
          latitude: 24.5764,
          longitude: 73.6794,
        },
        {
          name: 'Jaisalmer Desert Camp',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 3000,
          priceTo: 4800,
          currency: 'INR',
          address: 'Sam Sand Dunes, Jaisalmer',
          description: 'Swiss tents with camel safari and folk dances.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Camel ride', 'Bonfire'],
          latitude: 26.8500,
          longitude: 70.5333,
        },
        {
          name: 'Jaipur Budget Hostel',
          rating: 4.0,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Bani Park, Jaipur',
          description: 'Backpacker hostel with dorms and common kitchen.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Dorm beds', 'Wi-Fi'],
          latitude: 26.9300,
          longitude: 75.7930,
        },
        {
          name: 'Udaipur Old Town Guest House',
          rating: 4.1,
          priceLevel: '$',
          priceFrom: 1000,
          priceTo: 1800,
          currency: 'INR',
          address: 'Old City lanes, Udaipur',
          description: 'Small guest house facing the lake and ghats.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Roof terrace'],
          latitude: 24.5790,
          longitude: 73.6820,
        },
      ],
    },

    // SIKKIM
    {
      name: 'Sikkim, India',
      country: 'India',
      tagline: 'Himalayan views and monasteries',
      image: 'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
      description:
        'Sikkim is known for its high peaks, monasteries and clean towns.',
      topAttractions: ['Gangtok', 'Tsomgo Lake', 'Pelling'],
      themes: ['mountain', 'spiritual', 'nature'],
      popularityScore: 86,
      visitCount: 540,
      latitude: 27.5330,
      longitude: 88.5122,
      hotels: [
        {
          name: 'Gangtok MG Marg Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'MG Marg, Gangtok',
          description: 'Central hotel with easy access to shops and cafes.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Wi-Fi', 'Breakfast'],
          latitude: 27.3270,
          longitude: 88.6120,
        },
        {
          name: 'Tsomgo Lake View Resort',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 3000,
          priceTo: 4800,
          currency: 'INR',
          address: 'Near Tsomgo Lake, Sikkim',
          description: 'Resort nestled in the mountains near the lake.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Heater', 'Restaurant'],
          latitude: 27.3755,
          longitude: 88.7631,
        },
        {
          name: 'Pelling Monastery View Hotel',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4100,
          currency: 'INR',
          address: 'Upper Pelling',
          description: 'Hotel with views of Kanchenjunga on clear days.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Balcony', 'Room service'],
          latitude: 27.2990,
          longitude: 88.2410,
        },
        {
          name: 'Gangtok Backpackers Hostel',
          rating: 4.1,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Near Deorali, Gangtok',
          description: 'Backpacker hostel with common lounge and games.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Dorm beds', 'Wi-Fi'],
          latitude: 27.3200,
          longitude: 88.6100,
        },
        {
          name: 'Budget Inn Pelling',
          rating: 3.8,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1500,
          currency: 'INR',
          address: 'Lower Pelling',
          description: 'Simple rooms for travellers exploring west Sikkim.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Room service'],
          latitude: 27.2850,
          longitude: 88.2400,
        },
      ],
    },

    // TELANGANA
    {
      name: 'Telangana, India',
      country: 'India',
      tagline: 'Charminar city and waterfalls',
      image: 'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
      description:
        'Telangana is known for Hyderabad, historic sites and natural getaways.',
      topAttractions: ['Hyderabad', 'Warangal', 'Nagarjuna Sagar'],
      themes: ['city', 'heritage', 'nature'],
      popularityScore: 88,
      visitCount: 820,
      latitude: 18.1124,
      longitude: 79.0193,
      hotels: [
        {
          name: 'Hyderabad Hitech City Hotel',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 3200,
          priceTo: 5200,
          currency: 'INR',
          address: 'Hitech City, Hyderabad',
          description: 'Business hotel close to IT hubs and malls.',
          images: [
            'https://images.pexels.com/photos/37347/office-night-computer-innovation-37347.jpeg',
          ],
          amenities: ['Wi-Fi', 'Gym'],
          latitude: 17.4483,
          longitude: 78.3908,
        },
        {
          name: 'Charminar Old City Inn',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 3900,
          currency: 'INR',
          address: 'Old City, Hyderabad',
          description: 'Stay close to Charminar and local bazaars.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Breakfast', 'Parking'],
          latitude: 17.3616,
          longitude: 78.4747,
        },
        {
          name: 'Warangal Fort View Hotel',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2300,
          priceTo: 3600,
          currency: 'INR',
          address: 'Near Warangal Fort, Warangal',
          description: 'Hotel for exploring the old capital city.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Wi-Fi'],
          latitude: 17.9689,
          longitude: 79.5941,
        },
        {
          name: 'Nagarjuna Sagar Lake Resort',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4000,
          currency: 'INR',
          address: 'Nagarjuna Sagar, Telangana',
          description: 'Resort with dam and lake views.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Boating help', 'Restaurant'],
          latitude: 16.5750,
          longitude: 79.3167,
        },
        {
          name: 'Hyderabad Budget Hostel',
          rating: 4.0,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Banjara Hills, Hyderabad',
          description: 'Backpacker hostel with shared spaces and events.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Dorm beds', 'Wi-Fi'],
          latitude: 17.4180,
          longitude: 78.4480,
        },
      ],
    },

    // TRIPURA
    {
      name: 'Tripura, India',
      country: 'India',
      tagline: 'Palaces and lakes',
      image: 'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
      description:
        'Tripura is a small state with palaces, lakes and hills.',
      topAttractions: ['Agartala', 'Ujjayanta Palace', 'Neermahal'],
      themes: ['heritage', 'city', 'nature'],
      popularityScore: 68,
      visitCount: 240,
      latitude: 23.9408,
      longitude: 91.9882,
      hotels: [
        {
          name: 'Agartala City Hotel',
          rating: 4.0,
          priceLevel: '$$',
          priceFrom: 2100,
          priceTo: 3300,
          currency: 'INR',
          address: 'Central Agartala',
          description: 'Modern city hotel close to markets and bus stand.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Wi-Fi', 'Breakfast'],
          latitude: 23.8315,
          longitude: 91.2868,
        },
        {
          name: 'Ujjayanta Palace View Inn',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2200,
          priceTo: 3400,
          currency: 'INR',
          address: 'Near Ujjayanta Palace, Agartala',
          description: 'Stay near the famous palace and museum.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Parking', 'Room service'],
          latitude: 23.8340,
          longitude: 91.2822,
        },
        {
          name: 'Neermahal Lake Resort',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2400,
          priceTo: 3700,
          currency: 'INR',
          address: 'Rudrasagar Lake, Tripura',
          description: 'Resort with boat access to the water palace.',
          images: [
            'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
          ],
          amenities: ['Boating help', 'Restaurant'],
          latitude: 23.5435,
          longitude: 91.3617,
        },
        {
          name: 'Agartala Budget Lodge',
          rating: 3.7,
          priceLevel: '$',
          priceFrom: 800,
          priceTo: 1500,
          currency: 'INR',
          address: 'Agartala Town',
          description: 'Basic lodge for budget travellers.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['24/7 front desk'],
          latitude: 23.8310,
          longitude: 91.2875,
        },
        {
          name: 'Tripura Homely Stay',
          rating: 3.9,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1600,
          currency: 'INR',
          address: 'Suburb of Agartala',
          description: 'Homestay with local family and food.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Home-cooked meals'],
          latitude: 23.8400,
          longitude: 91.3000,
        },
      ],
    },

    // UTTAR PRADESH
    {
      name: 'Uttar Pradesh, India',
      country: 'India',
      tagline: 'Taj Mahal, ghats and heritage',
      image: 'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
      description:
        'Uttar Pradesh has iconic monuments, holy cities and rich history.',
      topAttractions: ['Agra', 'Varanasi', 'Lucknow'],
      themes: ['heritage', 'spiritual', 'city'],
      popularityScore: 93,
      visitCount: 1300,
      latitude: 26.8467,
      longitude: 80.9462,
      hotels: [
        {
          name: 'Agra Taj View Hotel',
          rating: 4.6,
          priceLevel: '$$',
          priceFrom: 3400,
          priceTo: 5600,
          currency: 'INR',
          address: 'Taj Ganj, Agra',
          description: 'Hotel with rooftop views of the Taj Mahal.',
          images: [
            'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
          ],
          amenities: ['Rooftop restaurant', 'Wi-Fi'],
          latitude: 27.1751,
          longitude: 78.0421,
        },
        {
          name: 'Agra Fort Side Inn',
          rating: 4.2,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'Near Agra Fort, Agra',
          description: 'Easy access to both Taj and fort.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Breakfast', 'Parking'],
          latitude: 27.1795,
          longitude: 78.0211,
        },
        {
          name: 'Varanasi Ghat Heritage Hotel',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 2800,
          priceTo: 4300,
          currency: 'INR',
          address: 'Dashashwamedh Ghat, Varanasi',
          description: 'Stay right on the ghats for morning aarti.',
          images: [
            'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
          ],
          amenities: ['River view', 'Restaurant'],
          latitude: 25.3064,
          longitude: 83.0103,
        },
        {
          name: 'Lucknow Hazratganj Hotel',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4100,
          currency: 'INR',
          address: 'Hazratganj, Lucknow',
          description: 'Central hotel for food and heritage walks.',
          images: [
            'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg',
          ],
          amenities: ['Wi-Fi', 'Gym'],
          latitude: 26.8500,
          longitude: 80.9462,
        },
        {
          name: 'Varanasi Budget Guest House',
          rating: 3.9,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Old City lanes, Varanasi',
          description: 'Small guest house with rooftop cafe.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Rooftop seating'],
          latitude: 25.3060,
          longitude: 83.0100,
        },
      ],
    },

    // UTTARAKHAND
    {
      name: 'Uttarakhand, India',
      country: 'India',
      tagline: 'Char Dham, lakes and mountains',
      image: 'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
      description:
        'Uttarakhand offers pilgrimage sites, hill stations and treks.',
      topAttractions: ['Rishikesh', 'Nainital', 'Mussoorie'],
      themes: ['spiritual', 'mountain', 'adventure'],
      popularityScore: 88,
      visitCount: 840,
      latitude: 30.0668,
      longitude: 79.0193,
      hotels: [
        {
          name: 'Rishikesh Ganga View Ashram Hotel',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'Laxman Jhula Road, Rishikesh',
          description: 'Stay facing the Ganga with yoga options.',
          images: [
            'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
          ],
          amenities: ['Yoga hall', 'Vegetarian meals'],
          latitude: 30.1290,
          longitude: 78.3220,
        },
        {
          name: 'Nainital Lakefront Hotel',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 3000,
          priceTo: 4800,
          currency: 'INR',
          address: 'Mall Road, Nainital',
          description: 'Hotel right on the lake with balcony rooms.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Boating help', 'Breakfast'],
          latitude: 29.3925,
          longitude: 79.4542,
        },
        {
          name: 'Mussoorie Mall Road Resort',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2800,
          priceTo: 4300,
          currency: 'INR',
          address: 'The Mall Road, Mussoorie',
          description: 'Resort with Doon valley views.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Bonfire', 'Restaurant'],
          latitude: 30.4599,
          longitude: 78.0644,
        },
        {
          name: 'Rishikesh Backpackers Hostel',
          rating: 4.2,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Tapovan, Rishikesh',
          description: 'Hostel popular with yoga and rafting crowd.',
          images: [
            'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg',
          ],
          amenities: ['Dorm beds', 'Common kitchen'],
          latitude: 30.1369,
          longitude: 78.3444,
        },
        {
          name: 'Budget Inn Nainital',
          rating: 3.8,
          priceLevel: '$',
          priceFrom: 1000,
          priceTo: 1800,
          currency: 'INR',
          address: 'Near Bus Stand, Nainital',
          description: 'Budget stay for families and groups.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Room service'],
          latitude: 29.3820,
          longitude: 79.4630,
        },
      ],
    },

    // WEST BENGAL
    {
      name: 'West Bengal, India',
      country: 'India',
      tagline: 'Colonial charm, hills and mangroves',
      image: 'https://images.pexels.com/photos/262367/pexels-photo-262367.jpeg',
      description:
        'West Bengal has Kolkata, Darjeeling hills and Sundarbans mangroves.',
      topAttractions: ['Kolkata', 'Darjeeling', 'Sundarbans'],
      themes: ['city', 'mountain', 'wildlife'],
      popularityScore: 87,
      visitCount: 780,
      latitude: 22.9868,
      longitude: 87.8550,
      hotels: [
        {
          name: 'Kolkata Park Street Hotel',
          rating: 4.4,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4200,
          currency: 'INR',
          address: 'Park Street, Kolkata',
          description: 'Central hotel close to restaurants and heritage areas.',
          images: [
            'https://images.pexels.com/photos/374710/pexels-photo-374710.jpeg',
          ],
          amenities: ['Wi-Fi', 'Breakfast'],
          latitude: 22.5525,
          longitude: 88.3528,
        },
        {
          name: 'Howrah Riverside Inn',
          rating: 4.1,
          priceLevel: '$$',
          priceFrom: 2300,
          priceTo: 3600,
          currency: 'INR',
          address: 'Howrah riverside, Kolkata',
          description: 'Stay facing the Hooghly river and bridge.',
          images: [
            'https://images.pexels.com/photos/127160/pexels-photo-127160.jpeg',
          ],
          amenities: ['River view', 'Restaurant'],
          latitude: 22.5958,
          longitude: 88.2636,
        },
        {
          name: 'Darjeeling Tea Garden Resort',
          rating: 4.5,
          priceLevel: '$$',
          priceFrom: 3200,
          priceTo: 5200,
          currency: 'INR',
          address: 'Near Tiger Hill, Darjeeling',
          description: 'Resort in tea gardens with views of Kanchenjunga.',
          images: [
            'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg',
          ],
          amenities: ['Guided walks', 'Bonfire'],
          latitude: 26.9855,
          longitude: 88.2850,
        },
        {
          name: 'Sundarbans Jungle Camp',
          rating: 4.3,
          priceLevel: '$$',
          priceFrom: 2600,
          priceTo: 4000,
          currency: 'INR',
          address: 'Sajnekhali area, Sundarbans',
          description: 'Camp with boat safaris in the mangroves.',
          images: [
            'https://images.pexels.com/photos/541416/pexels-photo-541416.jpeg',
          ],
          amenities: ['Safari desk', 'Meals included'],
          latitude: 22.1667,
          longitude: 88.7500,
        },
        {
          name: 'Kolkata Budget Guest House',
          rating: 3.8,
          priceLevel: '$',
          priceFrom: 900,
          priceTo: 1700,
          currency: 'INR',
          address: 'Near Esplanade, Kolkata',
          description: 'Simple stay suitable for backpackers and students.',
          images: [
            'https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg',
          ],
          amenities: ['Wi-Fi'],
          latitude: 22.5673,
          longitude: 88.3476,
        },
      ],
    },
  ]);


    console.log('Seeded destinations:', created.length);
    res.json(created);
  } catch (err) {
    console.error('Seed error:', err);
    res.status(500).json({ message: 'Seeding failed' });
  }
});

export default router;
